### ISSUE TITLE
Bad

### ISSUE THREAD

**Issue by Eruptsy** [QL0R/Python-Crypto-Price#1]
Why are you using system commands when u can use ANSI code. Also do u know using any type of system command in any type of app source is bad in the cyber security community ? https://github.com/0xDarkSky/Python-Crypto-Price/blob/5b71f239484b99981890aacac70a89c9602c7e82/crypto.py#L6

**Comment by 0xDarkSky** [comment]
No not really bad, unnecessary - yes. Just creates a child process shell, which can be prevented, not dangerous tho, especially in a basic program like this.
